Make it possible to install/uninstall/install a plugin bundle within one core session. Instead of deleting the Plugin record, instead we mark it as inactive. Then when installing plugins, we check if there is an inactive one that matches the new plugin exactly and if so, just mark it active.
There's a commit and a start session in there to give Romain
that icky feeling.

Just deleting the plugin record had issues when (re)installing
the same plugin, it kept throwing exceptions with
  ERROR: duplicate key violates unique constraint 'plugin_hashcode_key'
which I don't understand: I had just deleted the record with
that unique hashcode key. Maybe hibernate is caching something
extra here.