Add a spec for testing per project Metric selecting/deselecting. It doesn't work because of an NoClassDefFoundError exception related to MetricActivator that I don't understand.